### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by vanling** [becem-gharbi/nuxt-directus#42]
Not happening with `pnpm i` 

Tried `npm i` with and without `shamefully-hoist=true`
```
❯ npm i

> postinstall
> nuxt prepare

Nuxi 3.6.5                                                                                                                                                 1:50:14 PM

 ERROR  Error while requiring module nuxt-apollo: Error: Cannot find module '/Users/username/Sites/xxxx/gh-tpl/nuxt-apollo'                     1:50:15 PM
Require stack:
- /Users/username/Sites/xxxx/gh-tpl/index.js


 ERROR  Cannot find module '/Users/username/Sites/xxxx/gh-tpl/nuxt-apollo'                                                                      1:50:15 PM
Require stack:
- /Users/username/Sites/xxxx/gh-tpl/index.js

  Require stack:
  - index.js
  at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
  at Function.resolve (node:internal/modules/cjs/helpers:116:19)
  at Function._resolve [as resolve] (node_modules/jiti/dist/jiti.js:1:250100)
  at resolveModule (node_modules/@nuxt/kit/dist/index.mjs:2230:29)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2240:24)
  at loadNuxtModuleInstance (node_modules/@nuxt/kit/dist/index.mjs:2435:90)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2408:47)
  at async setup (node_modules/@bg-dev/nuxt-directus/dist/module.mjs:60:7)
  at async normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2140:17)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2409:95)

npm ERR! code 1
npm ERR! path /Users/username/Sites/xxxx/gh-tpl
npm ERR! command failed
npm ERR! command sh -c nuxt prepare
```

### Will try on a fresh nuxt installation later today

**Comment by becem-gharbi** [comment]
At the moment there is a dependency conflict at `nuxt-apollo` module. This prevents it from being installed at package root. As a workaround you can force installation
```
npm i nuxt-apollo --force
```

**Comment by becem-gharbi** [comment]
Mentioned this on new `nuxt-apollo` release [link](https://github.com/becem-gharbi/nuxt-apollo#known-issue).
